import React,{useState}from'react';
import{createRoot}from'react-dom/client';
import{Phone,Mail,MapPin,Car,CheckCircle,Globe,Send,ShieldCheck,Wrench,FileText,Fuel,Menu,X}from'lucide-react';
import{motion}from'framer-motion';
import'./style.css';

const T={
pl:{o:'Oferta',r:'Wymagania',a:'Zgłoszenie',h:'Auta dla kierowców Uber / Bolt',s:'Wynajem samochodów hybrydowych gotowych do pracy w Warszawie i okolicach.',p:'Od 400 zł / tydzień',c:'Zadzwoń',w:'WhatsApp',cars:'Toyota Prius+, Corolla Hybrid i inne hybrydy',why:'Dlaczego PRO-FIT?',req:'Wymagania',apply:'Zgłoszenie kierowcy',name:'Imię i nazwisko',phone:'Telefon',exp:'Czy jeździłeś już Uber/Bolt?',send:'Wyślij zgłoszenie na WhatsApp',docs:['Prawo jazdy kat. B','Zaświadczenie o niekaralności','Badania lekarskie','Psychotechnika','Odpowiedzialność i kultura osobista'],footer:'PRO-FIT Ireneusz Pleskot • Warszawa / Ząbki'},
en:{o:'Offer',r:'Requirements',a:'Apply',h:'Cars for Uber / Bolt drivers',s:'Hybrid cars ready for work in Warsaw and nearby areas.',p:'From 400 PLN / week',c:'Call',w:'WhatsApp',cars:'Toyota Prius+, Corolla Hybrid and other hybrids',why:'Why PRO-FIT?',req:'Requirements',apply:'Driver application',name:'Full name',phone:'Phone',exp:'Have you driven Uber/Bolt before?',send:'Send application via WhatsApp',docs:['Category B driving licence','Clean criminal record','Medical exam','Psychotechnical test','Responsibility and good manners'],footer:'PRO-FIT Ireneusz Pleskot • Warsaw / Ząbki'},
ua:{o:'Пропозиція',r:'Вимоги',a:'Заявка',h:'Авто для водіїв Uber / Bolt',s:'Гібридні авто готові до роботи у Варшаві та околицях.',p:'Від 400 зл / тиждень',c:'Подзвонити',w:'WhatsApp',cars:'Toyota Prius+, Corolla Hybrid та інші гібриди',why:'Чому PRO-FIT?',req:'Вимоги',apply:'Заявка водія',name:'Імʼя та прізвище',phone:'Телефон',exp:'Чи працювали ви вже в Uber/Bolt?',send:'Надіслати заявку у WhatsApp',docs:['Права категорії B','Довідка про несудимість','Медогляд','Психотести','Відповідальність і культура'],footer:'PRO-FIT Ireneusz Pleskot • Варшава / Зомбки'}};

function App(){
 const[lang,setLang]=useState('pl'),[menu,setMenu]=useState(false),[form,setForm]=useState({name:'',phone:'',exp:''}); const t=T[lang];
 const wa=()=>{const msg=`Zgłoszenie kierowcy PRO-FIT%0AImię: ${encodeURIComponent(form.name)}%0ATelefon: ${encodeURIComponent(form.phone)}%0ADoświadczenie: ${encodeURIComponent(form.exp)}`; window.open(`https://wa.me/48788999850?text=${msg}`,'_blank')};
 const fade={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true},transition:{duration:.55}};
 return <div className="page">
 <header><div className="brand">PRO-<span>FIT</span><small>RENT & DRIVE</small></div><nav className={menu?'open':''}><a href="#offer">{t.o}</a><a href="#req">{t.r}</a><a href="#apply">{t.a}</a><select value={lang}onChange={e=>setLang(e.target.value)}><option value="pl">PL</option><option value="en">EN</option><option value="ua">UA</option></select></nav><button className="menu"onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <section className="hero"><motion.div {...fade} className="heroText"><div className="badge"><MapPin size={18}/> Warszawa / Ząbki</div><h1>{t.h}</h1><p>{t.s}</p><div className="price">{t.p}</div><div className="actions"><a className="btn gold" href="tel:788999850"><Phone/> {t.c}: 788 999 850</a><a className="btn green" href="https://wa.me/48788999850" target="_blank"><Send/> {t.w}</a></div></motion.div><motion.div initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:.75}} className="carCard"><Car size={130}/><h2>{t.cars}</h2><p>Uber • Bolt • Hybrid • Taxi</p></motion.div></section>
 <section id="offer" className="section"><motion.h2 {...fade}>{t.why}</motion.h2><div className="grid">{[[Fuel,'Niskie spalanie / Low fuel use'],[Wrench,'Serwis i assistance'],[ShieldCheck,'Bezpieczna współpraca'],[FileText,'Pakiet dokumentów'],[Car,'Auta gotowe do pracy'],[Globe,'PL / EN / UA']].map(([Icon,text],i)=><motion.div {...fade} className="tile" key={i}><Icon/><h3>{text}</h3><p>Profesjonalna obsługa kierowców Uber/Bolt.</p></motion.div>)}</div></section>
 <section id="req" className="section dark"><motion.h2 {...fade}>{t.req}</motion.h2><div className="checks">{t.docs.map(x=><div className="check" key={x}><CheckCircle/> {x}</div>)}</div></section>
 <section id="apply" className="section apply"><motion.div {...fade} className="formBox"><h2>{t.apply}</h2><input placeholder={t.name} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder={t.phone} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><textarea placeholder={t.exp} value={form.exp} onChange={e=>setForm({...form,exp:e.target.value})}/><button onClick={wa}><Send/> {t.send}</button></motion.div></section>
 <footer><b>{t.footer}</b><br/>ul. Skrajna 32D/11, 05-091 Ząbki • NIP 1132499907<br/><a href="tel:788999850">788 999 850</a> • <a href="mailto:profitpl.pl@gmail.com">profitpl.pl@gmail.com</a></footer>
 </div>}
createRoot(document.getElementById('root')).render(<App/>);
